### PR TITLE
Button Styling & Roommate Coloring

### PR DESCRIPTION
**Pull request by va-wei**
- fixed contact table to correctly show username upon submission, works with database
- preferences form only shows up if there is not a submission to the table
- fixed status checkbox (retains checked checkbox when completed, unchecked goes back to pending)
- allow chore form submissions to include color for roommate assigned to
- welcome back message displaying the current user's username

### CODE REVIEW

**Review by ewong128 — APPROVED** [review]
Nice additional features. A suggestion that could be included is that for the color picker could be more appealing such that it is not just a square. Maybe include a color picker hexagon instead of the color box.

**Review by SukhmanKaur1 — APPROVED** [review]
Everything looks great, I really like the color option and how clean the roommate agreement form looks. A suggestion is instead of having to pick a color for a roommate each time, you could have one color assigned to the roommate.

**Comment by va-wei** [comment]
> Nice additional features. A suggestion that could be included is that for the color picker could be more appealing such that it is not just a square. Maybe include a color picker hexagon instead of the color box.

That's a good suggestion Emily, I'll see if i can work on that. I definitely agree that the box isn't the most appealing.

**Comment by va-wei** [comment]
> Everything looks great, I really like the color option and how clean the roommate agreement form looks. A suggestion is instead of having to pick a color for a roommate each time, you could have one color assigned to the roommate.

I like this suggestion Sukhman! I did have this in mind when implementing this feature. I'll see what I can do with the time remaining.

**Review by rachelHartfelder — CHANGES_REQUESTED** [review]
Hi Vanessa!

I love the features you added. Allowing the users to pick a color for the chore is a fun feature that makes the UI more appealing to the eye. However, my favorite feature you added was the update to the status button. Keeping the checkbox checked when the page is refreshed and allowing the user to change the chore back to pending creates a better user experience. Also, I saw some nice updates to the preferences and emergency contact form. Great Job! 

However, before you merge this code to main I suggest that you increase the size of the welcome message on the home page. It is a very nice feature but hard to see. I also noticed that the welcome message does not appear on the roommate agreement form page. I suggest that you add that feature there as well. Again great work. I am excited to see these updates in main.

**Comment by revamoolky** [comment]
I love the addition of the adding a color choice whenever inputting an event, chore, or unavailability. It's really interesting the way in which HTML could do that. I think it might be better for the UX if there was a call to action or some sort of way to explain on the UI that feature so users are aware of what that does.

**Pull request merged**
