### PR TITLE
Invite Roommate Link + Groups

### PR DESCRIPTION
**Pull request by rachelHartfelder**
The code adds the following functionality:

- Invite link takes users to login page where the user can either login or sign up. 
- Special links were need to specify the next screen as well as the group the user will be joining
- Upon signing up the user will be sent to an invitation page where they can accept their invitation adding them to the group
- Roommates are now connected through the groups database
- The filtering of chores and events based on group id is still in progress

### CODE REVIEW

**Review by va-wei — CHANGES_REQUESTED** [review]
Nice implementation of inviting roommates to different groups! I can see your efforts with the console.log()'s scattered throughout the code and it seems like the functionality was tested thoroughly; however I think we should remember to remove these lines before submitting the final project. 
Also, it seems like you removed the logo on the Login page and I don't think that was the intention. Other than that, great work!

**Comment by ewong128** [comment]
Nice updates, I like the idea that the link can be shared among the other roommate groups and that the connection is mutual. It seems that the user can create an account when brought up with the invite link and the feature of filtering out chores/events would be a nice implementation.

**Comment by SukhmanKaur1** [comment]
Great additions! The invite link seamlessly guides users to the login page, enabling login or signup. The implementation of special links to define the next screen and group enhances user experience. Upon signup, users smoothly transition to an invitation page, facilitating group inclusion. Now, with roommates linked via the groups database, collaboration is streamlined. Looking forward to the completion of chore and event filtering based on group ID!

**Review by SukhmanKaur1 — COMMENTED** [review]
Great additions! The invite link seamlessly guides users to the login page, enabling login or signup. The implementation of special links to define the next screen and group enhances user experience. Upon signup, users smoothly transition to an invitation page, facilitating group inclusion. Now, with roommates linked via the groups database, collaboration is streamlined. Looking forward to the completion of chore and event filtering based on group ID!

**Review by ewong128 — APPROVED** [review]
Nice updates, I like the idea that the link can be shared among the other roommate groups and that the connection is mutual. It seems that the user can create an account when brought up with the invite link and the feature of filtering out chores/events would be a nice implementation.

**Review by va-wei — APPROVED** [review]
Hey Rachel,
looks great! I can see that you added the logo back to the login page and the functionality for the rest of the code looks well tested as I can see your tests with the shared database! Great work!

**Pull request merged**
