### PR TITLE
Calendar Display in Frontend

### PR DESCRIPTION
**Pull request by ewong128**
Created a calendar application. Currently, still need to connect the backend with the frontend. 
- Styling has been done with a teal appeal.
- The Calendar has the functionality of viewing the calendar in the month, week, and day view.
-Additionally, the day function on the calendar should be clickable where you can click the day and it lets the user go to the day view.
-The calendar does not hold any values as of right now, but will be done at some point.

### CODE REVIEW

**Review by SukhmanKaur1 — COMMENTED** [review]
Hi Emily, I see you have implented the calendar in frontend, but since you have not connected it to the backend, I would do another pull request when you have connected the two.

**Review by va-wei — CHANGES_REQUESTED** [review]
Hey Emily, 
The calendar code looks promising! I noticed that your code isn't updated with main so I'm not sure that the functionality will be 100% if we merged it. I also noticed some merge conflict code in there, so that also needs to be fixed. Overall, I love your efforts with the calendar but I think that more works needs to be done so that functionality is 100%. Great progress!

**Review by rachelHartfelder — CHANGES_REQUESTED** [review]
Hi Emily! Thank you for all your hard work on the calendar! The styling looks great! Unfortunately since the calendar is not yet synced with the databases, I think it would be a wise choice to hold off on pushing this code to main. Again, great work hopefully with more time, the calendar will be updated with the chores, events, and unavailabilities and it can be pushed to main.

**Comment by revamoolky** [comment]
I really appreciate your efforts on the calendar. The calendar code would add great UX to the web app. I think with these adjustments, we'll ensure that the functionality is fully operational. Great progress! there are some merge conflict markers that need to be resolved however but just letting you know!

**Pull request closed without merging**
